language: r
sudo: false
cache: packages
pandoc: false
latex: false

install:
  - true

script:
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_BRANCH
  - git diff --name-only ${TRAVIS_BRANCH}..HEAD
  - Rscript R/create-md.R
  - git add -A
  - git diff --cached
